// // doctorSlice.js
// import { createSlice } from '@reduxjs/toolkit';
// import { searchDoctors } from './api'; // Import the API function

// export const doctorSlice = createSlice({
//   name: 'doctor',
//   initialState: {
//     doctors: [],
//     loading: false,
//     error: null
//   },
//   reducers: {
//     // No need to define action creators here, as Redux Toolkit automatically generates them
//   },
//   extraReducers: (builder) => {
//     builder
//       .addCase(searchDoctors.pending, (state) => {
//         state.loading = true;
//         state.error = null;
//       })
//       .addCase(searchDoctors.fulfilled, (state, action) => {
//         state.loading = false;
//         state.doctors = action.payload;
//         state.error = null;
//       })
//       .addCase(searchDoctors.rejected, (state, action) => {
//         state.loading = false;
//         state.error = action.error.message;
//       });
//   },
// });

// // Export action creators generated by createSlice
// export const { } = doctorSlice.actions;

// // Export the reducer
// export default doctorSlice.reducer;
